//
// File generated by /afs/cern.ch/sw/lcg/app/releases/ROOT/5.34.10/x86_64-slc6-gcc48-opt/root/bin/rootcint at Wed Apr 30 20:53:07 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME rootdict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "rootdict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Main_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Main(void *p = 0);
   static void *newArray_Main(Long_t size, void *p);
   static void delete_Main(void *p);
   static void deleteArray_Main(void *p);
   static void destruct_Main(void *p);
   static void streamer_Main(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Main*)
   {
      ::Main *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Main >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Main", ::Main::Class_Version(), "./Main.h", 11,
                  typeid(::Main), DefineBehavior(ptr, ptr),
                  &::Main::Dictionary, isa_proxy, 0,
                  sizeof(::Main) );
      instance.SetNew(&new_Main);
      instance.SetNewArray(&newArray_Main);
      instance.SetDelete(&delete_Main);
      instance.SetDeleteArray(&deleteArray_Main);
      instance.SetDestructor(&destruct_Main);
      instance.SetStreamerFunc(&streamer_Main);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Main*)
   {
      return GenerateInitInstanceLocal((::Main*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Main*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Main::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Main::Class_Name()
{
   return "Main";
}

//______________________________________________________________________________
const char *Main::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Main*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Main::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Main*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Main::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Main*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Main::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Main*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Main::Streamer(TBuffer &R__b)
{
   // Stream an object of class Main.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b.StreamObject(&(args),typeid(auto_ptr<TList>));
      R__b.CheckByteCount(R__s, R__c, Main::IsA());
   } else {
      R__c = R__b.WriteVersion(Main::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b.StreamObject(&(args),typeid(auto_ptr<TList>));
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void Main::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Main.
      TClass *R__cl = ::Main::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "args", (void*)&args);
      R__insp.InspectMember("auto_ptr<TList>", (void*)&args, "args.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Main(void *p) {
      return  p ? new(p) ::Main : new ::Main;
   }
   static void *newArray_Main(Long_t nElements, void *p) {
      return p ? new(p) ::Main[nElements] : new ::Main[nElements];
   }
   // Wrapper around operator delete
   static void delete_Main(void *p) {
      delete ((::Main*)p);
   }
   static void deleteArray_Main(void *p) {
      delete [] ((::Main*)p);
   }
   static void destruct_Main(void *p) {
      typedef ::Main current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_Main(TBuffer &buf, void *obj) {
      ((::Main*)obj)->::Main::Streamer(buf);
   }
} // end of namespace ROOT for class ::Main

/********************************************************
* rootdict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablerootdict();

extern "C" void G__set_cpp_environmentrootdict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Main.h");
  G__cpp_reset_tagtablerootdict();
}
#include <new>
extern "C" int G__cpp_dllrevrootdict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Main */
static int G__rootdict_192_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Main* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Main[n];
     } else {
       p = new((void*) gvp) Main[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Main;
     } else {
       p = new((void*) gvp) Main;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_Main));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Main* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Main((TList*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) Main((TList*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_Main));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Main*) G__getstructoffset())->run());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Main::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Main::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Main::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Main::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Main*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Main::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Main::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Main::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__rootdict_192_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Main::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__rootdict_192_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Main* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Main(*(Main*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__rootdictLN_Main));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Main G__TMain;
static int G__rootdict_192_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Main*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Main*) (soff+(sizeof(Main)*i)))->~G__TMain();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Main*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Main*) (soff))->~G__TMain();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__rootdict_192_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Main* dest = (Main*) G__getstructoffset();
   *dest = *(Main*) libp->para[0].ref;
   const Main& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Main */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncrootdict {
 public:
  G__Sizep2memfuncrootdict(): p(&G__Sizep2memfuncrootdict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncrootdict::*p)();
};

size_t G__get_sizep2memfuncrootdict()
{
  G__Sizep2memfuncrootdict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancerootdict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__rootdictLN_Main))) {
     Main *G__Lderived;
     G__Lderived=(Main*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__rootdictLN_Main),G__get_linked_tagnum(&G__rootdictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablerootdict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Main */
static void G__setup_memvarMain(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__rootdictLN_Main));
   { Main *p; p=(Main*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__rootdictLN_auto_ptrlETListgR),-1,-1,4,"args=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__rootdictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarrootdict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMain(void) {
   /* Main */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__rootdictLN_Main));
   G__memfunc_setup("Main",389,G__rootdict_192_0_1, 105, G__get_linked_tagnum(&G__rootdictLN_Main), -1, 0, 0, 1, 1, 0, "", "needed by Root IO", (void*) NULL, 0);
   G__memfunc_setup("Main",389,G__rootdict_192_0_2, 105, G__get_linked_tagnum(&G__rootdictLN_Main), -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - args", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("run",341,G__rootdict_192_0_3, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__rootdict_192_0_4, 85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Main::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__rootdict_192_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Main::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__rootdict_192_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Main::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__rootdict_192_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Main::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__rootdictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__rootdict_192_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__rootdict_192_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Main::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__rootdict_192_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Main::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__rootdict_192_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Main::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__rootdict_192_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Main::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Main", 389, G__rootdict_192_0_16, (int) ('i'), G__get_linked_tagnum(&G__rootdictLN_Main), -1, 0, 1, 1, 1, 0, "u 'Main' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Main", 515, G__rootdict_192_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__rootdict_192_0_18, (int) ('u'), G__get_linked_tagnum(&G__rootdictLN_Main), -1, 1, 1, 1, 1, 0, "u 'Main' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncrootdict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalrootdict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcrootdict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__rootdictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__rootdictLN_Main = { "Main" , 99 , -1 };
G__linked_taginfo G__rootdictLN_auto_ptrlETListgR = { "auto_ptr<TList>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablerootdict() {
  G__rootdictLN_TClass.tagnum = -1 ;
  G__rootdictLN_TBuffer.tagnum = -1 ;
  G__rootdictLN_TMemberInspector.tagnum = -1 ;
  G__rootdictLN_TObject.tagnum = -1 ;
  G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_TList.tagnum = -1 ;
  G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__rootdictLN_Main.tagnum = -1 ;
  G__rootdictLN_auto_ptrlETListgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablerootdict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__rootdictLN_TClass);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TObject);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_TList);
   G__get_linked_tagnum_fwd(&G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__rootdictLN_Main),sizeof(Main),-1,61696,"needed for Cint",G__setup_memvarMain,G__setup_memfuncMain);
   G__get_linked_tagnum_fwd(&G__rootdictLN_auto_ptrlETListgR);
}
extern "C" void G__cpp_setuprootdict(void) {
  G__check_setup_version(30051515,"G__cpp_setuprootdict()");
  G__set_cpp_environmentrootdict();
  G__cpp_setup_tagtablerootdict();

  G__cpp_setup_inheritancerootdict();

  G__cpp_setup_typetablerootdict();

  G__cpp_setup_memvarrootdict();

  G__cpp_setup_memfuncrootdict();
  G__cpp_setup_globalrootdict();
  G__cpp_setup_funcrootdict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncrootdict();
  return;
}
class G__cpp_setup_initrootdict {
  public:
    G__cpp_setup_initrootdict() { G__add_setup_func("rootdict",(G__incsetup)(&G__cpp_setuprootdict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initrootdict() { G__remove_setup_func("rootdict"); }
};
G__cpp_setup_initrootdict G__cpp_setup_initializerrootdict;

