########################################################################
# J/psi(1S) -> mu mu
#
# This DaVinci script runs over MC J/psi(1S) -> mu+ mu-,
# such as that generated by the Gauss particle gun configuration ../gauss/JpsiGun.py
# (or bookkeeping MC)
# It saves the invariant mass of the dimuon, i.e. the observed J/psi mass after FSR
#
# @author Jack Wimberley
# @date 2013-10-11
########################################################################

from Gaudi.Configuration import *
from Configurables import DaVinci
from GaudiKernel.SystemOfUnits import *

# -------
# OPTIONS
# -------

MessageSvc().OutputLevel = INFO
DaVinci().EvtMax = -1
DaVinci().PrintFreq = 100
DaVinci().HistogramFile = "PythiaBJpsiK_histos.root"
DaVinci().TupleFile = "PythiaBJpsiK.root"

DaVinci().DataType = "2012"
from Configurables import CondDB
CondDB().UseLatestTags = ["2012"]

# --------------
# MC TRUTH TUPLE
# --------------

from Configurables import DecayTreeTuple, MCDecayTreeTuple
from DecayTreeTuple.Configuration import *
mudecay = "[B+ => ^(J/psi(1S) => ^mu+ ^mu-) ^K+]CC"
tuple = MCDecayTreeTuple("PythiaJpsiTuple")
tuple.TupleName = "DecayTree"
tuple.addBranches({
    "B" : "[^(B+ -> (J/psi(1S) -> mu+ mu-) K+)]CC"
    , "Jpsi" : "[B+ -> ^(J/psi(1S) -> mu+ mu-) K+]CC"
    , "MuP" : "[B+ -> (J/psi(1S) -> ^mu+ mu-) K+]CC"
    , "MuM" : "[B+ -> (J/psi(1S) -> mu+ ^mu-) K+]CC"
    , "K" : "[B+ -> (J/psi(1S) -> mu+ mu-) ^K+]CC"
    })
tuple.Decay = mudecay
tuple.ToolList = []
from Configurables import LoKi__Hybrid__TupleTool
from Configurables import LoKi__Hybrid__MCTupleTool
LTT = tuple.addTupleTool("LoKi::Hybrid::MCTupleTool/LTT")
LTT.Preambulo += ["from LoKiCore.functions import *"]
LTT.Variables = {
    "MCE" : "MCE"
    , "MCETA" : "MCETA"
    , "MCP" : "MCP"
    , "MCPX" : "MCPX"
    , "MCPY" : "MCPY"
    , "MCPZ" : "MCPZ"
    , "MCPT" : "MCPT"
    , "MCTHETA" : "MCTHETA"
    , "MCPHI" : "MCPHI"
    }
BLTT = tuple.B.addTupleTool("LoKi::Hybrid::MCTupleTool/BLTT")
BLTT.Preambulo += [
    "from LoKiCore.functions import *"
    , "from LoKiCore.math import *"
    , "E = MCCHILD(MCE,1) + MCCHILD(MCE,2)"
    , "PX = MCCHILD(MCPX,1) + MCCHILD(MCPX,2)"
    , "PY = MCCHILD(MCPY,1) + MCCHILD(MCPY,2)"
    , "PZ = MCCHILD(MCPZ,1) + MCCHILD(MCPZ,2)"
    ]
BLTT.Variables = { "MM" : "sqrt(E*E - PX*PX - PY*PY - PZ*PZ)/1000" }
JpsiLTT = tuple.Jpsi.addTupleTool("LoKi::Hybrid::MCTupleTool/JpsiLTT")
JpsiLTT.Preambulo += [
    "from LoKiCore.functions import *"
    , "from LoKiCore.math import *"
    , "E = MCCHILD(MCE,1) + MCCHILD(MCE,2)"
    , "PX = MCCHILD(MCPX,1) + MCCHILD(MCPX,2)"
    , "PY = MCCHILD(MCPY,1) + MCCHILD(MCPY,2)"
    , "PZ = MCCHILD(MCPZ,1) + MCCHILD(MCPZ,2)"
    ]
JpsiLTT.Variables = { "MM" : "sqrt(E*E - PX*PX - PY*PY - PZ*PZ)/1000" }


DaVinci().appendToMainSequence( [ tuple ] )
