#!/bin/sh
gaudirun.py 30000000.py Gauss-Job.py


#$APPCONFIGOPTS/Gauss/Beam3500GeV-mu100-MC11-nu2.py;
#$DECFILESROOT/options/@{eventType}.py;
#$LBGENXICCROOT/options/GenXicc.py;
#$APPCONFIGOPTS/Gauss/GenXicc_ProdFix.py;
#$APPCONFIGOPTS/Gauss/G4PL_LHEP_EmNoCuts.py 
